Add Letra Extension
mattjegan/awesome-hacktoberfest pull request #90
Opened 2020-10-15 00:58 UTC by vanestorz

Add first timers javascript repository.

2020-10-19 02:41 UTC, vanestorz commented
@mattjegan could you please review my PR?

2020-10-21 23:09 UTC, koppor commented
This is an awesome extension. I love it. Please link only the source code repository. It contains a description, too. Furthermore, this makes the item consistent to the others.

May I ask you to follow our contributing.md?

![grafik](https://user-images.githubusercontent.com/1366654/96799290-18e43b00-1403-11eb-982e-bbc4ed9378e7.png)

May I ask whether our CONTRIBUTING.md is too long? How could we ensure that these requriments are followed?

2020-10-22 05:59 UTC, vanestorz commented
> This is an awesome extension. I love it. Please link only the source code repository. It contains a description, too. Furthermore, this makes the item consistent to the others.
> 
> May I ask you to follow our contributing.md?
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/96799290-18e43b00-1403-11eb-982e-bbc4ed9378e7.png)
> 
> May I ask whether our CONTRIBUTING.md is too long? How could we ensure that these requriments are followed?

For the description and the link to the official project website i refer to React and React Native section, but i already removed the description and only put the repository link only. For the Contributing.md i truly apologize i misread on some parts and make PR carelessly.

Hope you can re-review my PR and also give a suggestion to make this project better! thanks.

2020-10-24 09:38 UTC, koppor requested changes

2020-10-24 09:38 UTC, koppor commented on readme.md
> +
Why the additional empty line?

2020-10-24 09:38 UTC, koppor commented on readme.md
> +- [letra-extension](https://github.com/jayehernandez/letra-extension)
Where is the description gone? In your first proposal, you had a description, which was good as far as I remember.

2020-11-03 19:49 UTC, koppor commented
I fixed it for myself at https://github.com/mattjegan/awesome-hacktoberfest/commit/f240bcc4448c74053dc9efb8f673dd5d3a30861a. Thank you for the inspiration

2020-11-03 19:49 UTC, closed without merging